

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dtu-mlops-object-detection/od_trainer', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtu-mlops-object-detection/od_trainer']
