results_input_dir: outputs\2023-01-18\11-56-30\
images_input_dir: C:\Users\ditte\dtu_ml_ops\2023-DTU-MLOps-Object-Detection\data\raw\coco\images\val2017 #E:/mlops/data/raw/voc/VOCdevkit/VOC2007/JPEGImages #coco/images/val2017/
image_no: 0